### ISSUE TITLE
Mutations when no error model specified

### ISSUE THREAD

**Issue by chadsmith123** [zyxue/biogrinder#2]
When no error model is specified the sequences are different than the template. 
 
The template is:
>test1
GTCGAATCGAATCGAATCGAATCGAATCGAATCGAATCGAATCGAATCGAATCGAATCGAATCGAATCGAATCGAATCGAATCGAATCGAATCGAATCA

Attached is the alignment with muscle after running:
grinder -rf test1.fasta -tr 50 -rd 100 -bn ${i}_none

![grinder](https://user-images.githubusercontent.com/10212078/44880754-44739c80-ac62-11e8-9137-ec61e8f95bba.PNG)

**Comment by zyxue** [comment]
>I created this repo of biogrinder mainly for reading the README.md in a better formatted and easier way.

Please contact the author of Grinder for potential problems.
