### ISSUE TITLE
Can not get defined abundance

### ISSUE THREAD

**Issue by ma-celik** [zyxue/biogrinder#3]
Hello,

Great work, i appreciate it so much but i am having a little problem. Eventho i ve tried many options i simply can not get the abundance that i specify. I.E. my abundance file looks like below, i should get an equal distribution right? Somehow the grinder-ranks.txt shows the abundance correct but in my grinder-reads.fa file does not yield equal distribution nor never gives me the specified distribution. I am posting the command that i am using altho I have tried it with many parameters . What am i doing wrong in here? Please help

`grinder -reference_file 16Sncbi.fasta -abundance_file abundance.txt
`
abundance.txt looks like below
NR_116675.1 0.1
NR_163665.1 0.1
NR_152690.1 0.1
NR_163664.1 0.1
NR_163663.1 0.1
NR_163662.1 0.1
NR_163661.1 0.1
NR_163660.1 0.1
NR_163659.1 0.1
NR_163658.1 0.1

**Comment by zyxue** [comment]
please try reaching out to the developer of grinder.
