### ISSUE TITLE
Installing grinder failed

### ISSUE THREAD

**Issue by najouamghazli** [zyxue/biogrinder#5]
Hello,

I've been trying to install Grinder on my macOS machine but I'am struggling with Bio::SeqIO module. 

After "installing" and running the command grinder-h I get this:

> Can't locate Bio/SeqIO.pm in @INC (you may need to install the Bio::SeqIO module) (@INC contains: /Users/imac/opt/anaconda3/bin /Users/imac/opt/anaconda3/lib/site_perl/5.26.2/darwin-thread-multi-2level /Users/imac/opt/anaconda3/lib/site_perl/5.26.2 /Users/imac/opt/anaconda3/lib/5.26.2/darwin-thread-multi-2level /Users/imac/opt/anaconda3/lib/5.26.2 .) at /Users/imac/opt/anaconda3/lib/site_perl/5.26.2/Grinder.pm line 11.
BEGIN failed--compilation aborted at /Users/imac/opt/anaconda3/lib/site_perl/5.26.2/Grinder.pm line 11.
Compilation failed in require at /Users/imac/opt/anaconda3/bin/grinder line 24.
BEGIN failed--compilation aborted at /Users/imac/opt/anaconda3/bin/grinder line 24.

The make command gives the following

> […]
9 dependencies missing (Graph::Directed,LWP::UserAgent,List::MoreUtils,Test::Memory::Cycle,XML::DOM,XML::LibXML,XML::LibXML::Reader,XML::Parser::PerlSAX,XML::Twig); additionally test harness failed
  /usr/bin/make test -- NOT OK
//hint// to see the cpan-testers results for installing this module, try:
  reports CJFIELDS/BioPerl-1.7.8.tar.gz
*** Bio::Root::Version installation failed.
*** Installing Bio::Location::Split...
Running install for module 'Bio::Location::Split'
  CJFIELDS/BioPerl-1.7.8.tar.gz
  Has already been unwrapped into directory /Users/imac/.cpan/build/BioPerl-1.7.8-6
  CJFIELDS/BioPerl-1.7.8.tar.gz
  Has already been prepared
  CJFIELDS/BioPerl-1.7.8.tar.gz
  Has already been made
  CJFIELDS/BioPerl-1.7.8.tar.gz
  Has already been tested within this command
*** Bio::Location::Split installation failed.
*** Installing Bio::Root::Root...
Running install for module 'Bio::Root::Root'
  CJFIELDS/BioPerl-1.7.8.tar.gz
  Has already been unwrapped into directory /Users/imac/.cpan/build/BioPerl-1.7.8-6
  CJFIELDS/BioPerl-1.7.8.tar.gz
  Has already been prepared
  CJFIELDS/BioPerl-1.7.8.tar.gz
  Has already been made
  CJFIELDS/BioPerl-1.7.8.tar.gz
  Has already been tested within this command
*** Bio::Root::Root installation failed.
*** Installing Bio::SeqIO...
Running install for module 'Bio::SeqIO'
  CJFIELDS/BioPerl-1.7.8.tar.gz
  Has already been unwrapped into directory /Users/imac/.cpan/build/BioPerl-1.7.8-6
  CJFIELDS/BioPerl-1.7.8.tar.gz
  Has already been prepared
  CJFIELDS/BioPerl-1.7.8.tar.gz
  Has already been made
  CJFIELDS/BioPerl-1.7.8.tar.gz
  Has already been tested within this command
*** Bio::SeqIO installation failed.
*** Installing Math::Random::MT...
Running install for module 'Math::Random::MT'
Checksum for /Users/imac/.cpan/sources/authors/id/F/FA/FANGLY/Math-Random-MT-1.17.tar.gz ok
Configuring F/FA/FANGLY/Math-Random-MT-1.17.tar.gz with Makefile.PL
Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for Math::Random::MT
Writing MYMETA.yml and MYMETA.json
  FANGLY/Math-Random-MT-1.17.tar.gz
  /Users/imac/opt/anaconda3/bin/perl Makefile.PL -- OK
Running make for F/FA/FANGLY/Math-Random-MT-1.17.tar.gz
cp MT.pm blib/lib/Math/Random/MT.pm
Running Mkbootstrap for MT ()
chmod 644 "MT.bs"
"/Users/imac/opt/anaconda3/bin/perl" -MExtUtils::Command::MM -e 'cp_nonempty' -- MT.bs blib/arch/auto/Math/Random/MT/MT.bs 644
"/Users/imac/opt/anaconda3/bin/perl" "/Users/imac/opt/anaconda3/lib/5.26.2/ExtUtils/xsubpp"  -typemap '/Users/imac/opt/anaconda3/lib/5.26.2/ExtUtils/typemap' -typemap '/Users/imac/.cpan/build/Math-Random-MT-1.17-4/typemap'  MT.xs > MT.xsc
mv MT.xsc MT.c
x86_64-apple-darwin13.4.0-clang -c   -fno-common -DPERL_DARWIN -no-cpp-precomp -mmacosx-version-min=10.9 -fno-strict-aliasing -pipe -fstack-protector-strong -DPERL_USE_SAFE_PUTENV -O3   -DVERSION=\"1.17\" -DXS_VERSION=\"1.17\" -fPIC --sysroot=/opt/MacOSX10.9.sdk "-I/Users/imac/opt/anaconda3/lib/5.26.2/darwin-thread-multi-2level/CORE"   MT.c
/bin/sh: x86_64-apple-darwin13.4.0-clang: command not found
make[1]: *** [MT.o] Error 127
  FANGLY/Math-Random-MT-1.17.tar.gz
  /usr/bin/make -- NOT OK
*** Math::Random::MT installation failed.
*** Module::AutoInstall installation finished.
cp lib/Grinder/Database.pm blib/lib/Grinder/Database.pm
cp lib/Grinder/KmerCollection.pm blib/lib/Grinder/KmerCollection.pm
cp lib/Bio/PrimarySeqI.pm blib/lib/Bio/PrimarySeqI.pm
cp lib/Bio/PrimarySeq.pm blib/lib/Bio/PrimarySeq.pm
cp lib/Bio/SeqFeature/Amplicon.pm blib/lib/Bio/SeqFeature/Amplicon.pm
cp lib/Bio/DB/Fasta.pm blib/lib/Bio/DB/Fasta.pm
cp lib/Grinder.pm blib/lib/Grinder.pm
cp lib/Bio/Seq/SimulatedRead.pm blib/lib/Bio/Seq/SimulatedRead.pm
cp lib/Bio/Seq/SeqFastaSpeedFactory.pm blib/lib/Bio/Seq/SeqFastaSpeedFactory.pm
cp lib/Bio/Tools/IUPAC.pm blib/lib/Bio/Tools/IUPAC.pm
cp lib/Bio/DB/IndexedBase.pm blib/lib/Bio/DB/IndexedBase.pm
cp lib/Bio/SeqFeature/SubSeq.pm blib/lib/Bio/SeqFeature/SubSeq.pm
cp lib/Bio/SeqFeature/Primer.pm blib/lib/Bio/SeqFeature/Primer.pm
cp lib/Bio/Tools/AmpliconSearch.pm blib/lib/Bio/Tools/AmpliconSearch.pm
cp utils/average_genome_size blib/script/average_genome_size
"/Users/imac/opt/anaconda3/bin/perl" "-Iinc" -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/average_genome_size
cp utils/change_paired_read_orientation blib/script/change_paired_read_orientation
"/Users/imac/opt/anaconda3/bin/perl" "-Iinc" -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/change_paired_read_orientation
cp script/grinder blib/script/grinder
"/Users/imac/opt/anaconda3/bin/perl" "-Iinc" -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/grinder
Manifying 2 pod documents
Manifying 13 pod documents

I don't know if it is related but Bio module is installed in python and it can import SeqIO.
Any help is appreciated.

Najoua

**Comment by najouamghazli** [comment]
I finally get to force install Bio::SeqIO, but now another problem arise. It's about Math::Random::MT that I can't install correctly on my machine for the following reason:

> In file included from MT.xs:2:
> 
> /Users/imac/opt/anaconda3/lib/5.26.2/darwin-thread-multi-2level/CORE/perl.h:694:10: fatal error: 'sys/types.h' file not found
> #include <sys/types.h>
>          ^~~~~~~~~~~~~
> 1 error generated.
> make: *** [MT.o] Error 1
>   FANGLY/Math-Random-MT-1.17.tar.gz
>   /usr/bin/make -- NOT OK

**Comment by zyxue** [comment]
you may try asking on https://sourceforge.net/p/biogrinder/discussion/.
